# Generated by Django 5.0.4 on 2025-03-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_mexican_guys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whopays',
            options={'verbose_name': 'Who pays?', 'verbose_name_plural': 'Who pays?'},
        ),
    ]
