# Generated by Django 5.0.4 on 2025-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_mexican_guys', '0002_alter_whopays_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='whopays',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
